### ISSUE TITLE
System.MissingMethodException on Windows 7

### ISSUE THREAD

**Issue by ghost** [AtomCrafty/windows-high-dpi-tests#1]
Hi!

Your program crashes with this exception:

![image](https://user-images.githubusercontent.com/40535137/45915772-442e8180-be5b-11e8-9bb5-284d1cd84288.png)

**Comment by ghost** [comment]
Oh, so this means one or more of those functions don't exist on windows 7, but then i can't find any information on which one is missing...

**Comment by ghost** [comment]
It seems that installing Microsoft .NET Framework 4.7.2 and Microsoft .NET Core SDK 2.1 fixed the problem. 

The missing functions are here: https://github.com/ppy/osu-framework/issues/1900#issuecomment-423734822

**Comment by AtomCrafty** [comment]
The fact that `System.__Canon` is part of the error message makes me think that was an issue with .Net itself (more specificly the JIT).
